AWSTemplateFormatVersion: '2010-09-09'
Description: mattcodes
Parameters:
  S3BucketName:
    Type: String
    Description: S3 Bucket Name to deploy to
    Default: mattcodes
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'S3BucketName'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      Tags:
        - Key: Owner
          Value: Matt Szabo
        - Key: Name
          Value: mattcodes
  WebsiteCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CloudFront distribution for mattcodes
        Aliases:
          - mattcodes.com.au
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:108801605866:certificate/935f9d2f-c49b-42bd-b815-19a20d732f2d
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
          ForwardedValues:
            Cookies:
              Forward: none
            Headers: []
            QueryString: 'false'
          SmoothStreaming: 'false'
          TargetOriginId: default-origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: '404'
            ResponsePagePath: '/404.html'
            ResponseCode: '200'
            ErrorCachingMinTTL: '30'
          - ErrorCode: '403'
            ResponsePagePath: '/403.html'
            ResponseCode: '200'
            ErrorCachingMinTTL: '30'
        Enabled: 'true'
        Origins:
          - DomainName: !GetAtt WebsiteBucket.DomainName
            Id: 'default-origin'
            S3OriginConfig: {}
        PriceClass: PriceClass_All
  MattcodesDNS:
    DependsOn: WebsiteCloudFront
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: mattcodes.com.au.
      RecordSets:
        - Name: mattcodes.com.au
          AliasTarget:
            DNSName: !GetAtt WebsiteCloudFront.DomainName
            HostedZoneId: 'Z2FDTNDATAQYW2'
          Type: A
        - Name: mattcodes.com.au
          AliasTarget:
            DNSName: !GetAtt WebsiteCloudFront.DomainName
            HostedZoneId: 'Z2FDTNDATAQYW2'
          Type: AAAA
        - Name: www.mattcodes.com.au
          AliasTarget:
            DNSName: mattcodes.com.au.
            HostedZoneId: 'Z2DRZUNLT7AKDR'
          Type: A
        - Name: www.mattcodes.com.au
          AliasTarget:
            DNSName: mattcodes.com.au.
            HostedZoneId: 'Z2DRZUNLT7AKDR'
          Type: AAAA
Outputs:
  WebsiteURL:
    Description: S3 Bucket Website URL
    Value: !GetAtt 'WebsiteBucket.WebsiteURL'
  DomainName:
    Description: CloudFront distribution domain for mattcodes
    Value: !GetAtt 'WebsiteCloudFront.DomainName'
